export const demoSeed = {
  accounts: [
    {
      studentNumber: "2023123456",
      password: "wenyuan88",
      profileId: "profile-pine",
    },
    {
      studentNumber: "2023000001",
      password: "editor88",
      profileId: "profile-editor",
    },
    {
      studentNumber: "2022111111",
      password: "reader88",
      profileId: "profile-dew",
    },
  ],
  profiles: [
    {
      id: "profile-pine",
      pen_name: "松声",
      bio: "在宿舍熄灯后写诗，也记录风穿过长安校区的声音。",
      role: "member",
      created_at: "2025-09-08T12:00:00+08:00",
      updated_at: "2026-07-20T12:00:00+08:00",
    },
    {
      id: "profile-editor",
      pen_name: "编辑部",
      bio: "整理来稿，也在每一篇新作下面认真读完。",
      role: "admin",
      created_at: "2025-08-20T12:00:00+08:00",
      updated_at: "2026-07-28T12:00:00+08:00",
    },
    {
      id: "profile-dew",
      pen_name: "白露",
      bio: "写散文，偶尔写很短的小说。",
      role: "member",
      created_at: "2025-10-02T12:00:00+08:00",
      updated_at: "2026-07-12T12:00:00+08:00",
    },
    {
      id: "profile-apricot",
      pen_name: "杏雨",
      bio: "把日常里没有说完的话留给纸页。",
      role: "member",
      created_at: "2026-02-14T12:00:00+08:00",
      updated_at: "2026-07-18T12:00:00+08:00",
    },
    {
      id: "profile-wild",
      pen_name: "原上",
      bio: "小说习作者，关心人如何在城市里彼此看见。",
      role: "member",
      created_at: "2025-11-03T12:00:00+08:00",
      updated_at: "2026-07-25T12:00:00+08:00",
    },
  ],
  works: [
    {
      id: "work-night-bus",
      author_id: "profile-pine",
      title: "末班车经过友谊校区",
      excerpt: "车窗把夜色裁成一格一格，路灯从旧教学楼的墙面上缓慢退去。",
      content:
        "车窗把夜色裁成一格一格\n路灯从旧教学楼的墙面上缓慢退去\n像有人合上一本读到一半的书\n\n末班车里没有人说话\n只有报站声一遍遍确认\n我们仍在城市之中\n\n我想起白天没有寄出的那封信\n纸页很薄，沉默却有重量\n\n车门打开时\n风先下了车",
      category: "诗歌",
      status: "published",
      is_featured: true,
      created_at: "2026-07-29T22:16:00+08:00",
      updated_at: "2026-07-29T22:16:00+08:00",
    },
    {
      id: "work-river",
      author_id: "profile-dew",
      title: "河流向北",
      excerpt: "祖父把地图折成很小的一块，塞进旧外套靠近心口的内袋。",
      content:
        "祖父把地图折成很小的一块，塞进旧外套靠近心口的内袋。\n\n他说年轻时沿着河走，方向并不重要，只要水声还在，村庄就不会真正离开。后来河道改了，桥也重修过几次，我们仍用旧名字称呼那些地方。\n\n今年春天我独自回去。岸边新种的杨树很细，风吹过时，所有叶子一起翻到明亮的一面。我突然明白，记忆不是要把什么留在原地，它只是给不断变化的事物留一个可以回望的方向。",
      category: "散文",
      status: "published",
      is_featured: true,
      created_at: "2026-07-28T18:40:00+08:00",
      updated_at: "2026-07-28T18:40:00+08:00",
    },
    {
      id: "work-balcony",
      author_id: "profile-apricot",
      title: "阳台上的七分钟",
      excerpt: "晾衣绳把傍晚分成两半，一半是洗净的衬衫，一半是还没暗下去的天空。",
      content:
        "晾衣绳把傍晚分成两半，一半是洗净的衬衫，一半是还没暗下去的天空。\n\n我给自己七分钟，不回消息，也不想明天。楼下的自行车铃响了两次，隔壁有人收起被单，远处的云慢慢移过实验楼。\n\n七分钟结束时，世界没有变得更容易。但我重新听见了自己的呼吸。",
      category: "随笔",
      status: "published",
      is_featured: false,
      created_at: "2026-07-27T19:08:00+08:00",
      updated_at: "2026-07-27T19:08:00+08:00",
    },
    {
      id: "work-unnamed-station",
      author_id: "profile-wild",
      title: "没有名字的车站",
      excerpt: "他每天在同一班地铁上醒来，却从未见过列车抵达终点。",
      content:
        "他每天在同一班地铁上醒来，却从未见过列车抵达终点。\n\n广播里所有站名都被一阵短促的电流声代替。乘客们对此习以为常，在该下车的时候自然起身，只有他不知道自己的站在哪里。\n\n第三十七天，一个抱着纸箱的女孩坐到他对面。纸箱里传出钟表走动的声音。女孩问：你是不是把要去的地方忘在出发之前了？",
      category: "小说",
      status: "published",
      is_featured: true,
      created_at: "2026-07-26T23:02:00+08:00",
      updated_at: "2026-07-26T23:02:00+08:00",
    },
    {
      id: "work-library-rain",
      author_id: "profile-editor",
      title: "雨落在图书馆闭馆以后",
      excerpt: "我们从旋转门里出来，手中各自握着一本没有读完的书。",
      content:
        "我们从旋转门里出来，手中各自握着一本没有读完的书。\n\n雨已经落了很久。台阶反射着灯光，像一段被擦亮的沉默。你说，明天再读吧。我点点头，却知道有些句子只属于今晚。\n\n后来我们撑开两把伞，向不同的宿舍走去。雨声很密，把没有说出口的话保存得很好。",
      category: "诗歌",
      status: "published",
      is_featured: false,
      created_at: "2026-07-25T22:30:00+08:00",
      updated_at: "2026-07-25T22:30:00+08:00",
    },
    {
      id: "work-small-things",
      author_id: "profile-dew",
      title: "小事记",
      excerpt: "记住一周里那些没有成为新闻的时刻。",
      content:
        "星期一，食堂阿姨多给了一勺汤。\n\n星期三，楼道尽头的灯终于修好。\n\n星期五，有人在操场边捡到一页手写诗，压在长椅上等失主回来。\n\n这些事情没有改变世界，但它们使这一周有了可以触摸的边缘。",
      category: "其他",
      status: "published",
      is_featured: false,
      created_at: "2026-07-24T16:12:00+08:00",
      updated_at: "2026-07-24T16:12:00+08:00",
    },
  ],
  likes: [
    { work_id: "work-night-bus", user_id: "profile-dew" },
    { work_id: "work-night-bus", user_id: "profile-editor" },
    { work_id: "work-river", user_id: "profile-pine" },
    { work_id: "work-river", user_id: "profile-editor" },
    { work_id: "work-river", user_id: "profile-apricot" },
    { work_id: "work-unnamed-station", user_id: "profile-pine" },
    { work_id: "work-unnamed-station", user_id: "profile-dew" },
    { work_id: "work-library-rain", user_id: "profile-pine" },
  ],
  comments: [
    {
      id: "comment-1",
      work_id: "work-night-bus",
      user_id: "profile-dew",
      parent_id: null,
      content: "最后一句让整首诗忽然有了风。",
      is_deleted: false,
      created_at: "2026-07-29T23:00:00+08:00",
      updated_at: "2026-07-29T23:00:00+08:00",
    },
    {
      id: "comment-2",
      work_id: "work-night-bus",
      user_id: "profile-pine",
      parent_id: "comment-1",
      content: "谢谢你读到最后。",
      is_deleted: false,
      created_at: "2026-07-29T23:12:00+08:00",
      updated_at: "2026-07-29T23:12:00+08:00",
    },
    {
      id: "comment-3",
      work_id: "work-river",
      user_id: "profile-apricot",
      parent_id: null,
      content: "“明亮的一面”这一处很喜欢。",
      is_deleted: false,
      created_at: "2026-07-28T20:18:00+08:00",
      updated_at: "2026-07-28T20:18:00+08:00",
    },
    {
      id: "comment-4",
      work_id: "work-unnamed-station",
      user_id: "profile-editor",
      parent_id: null,
      content: "设定很稳，期待继续写下去。",
      is_deleted: false,
      created_at: "2026-07-27T09:05:00+08:00",
      updated_at: "2026-07-27T09:05:00+08:00",
    },
  ],
  siteSettings: {
    editor_note: {
      title: "把写下的交给彼此",
      body: "这里持续收录社员的新作，也保留认真、具体、彼此尊重的讨论。无需等到某个刊期，写完就可以来到这里。",
    },
    submission: {
      title: "长期征稿",
      body: "诗歌、散文、小说、随笔与其他文字均可投稿。请确保作品为本人原创，并尊重评论区里的每一位读者。",
    },
    community_rules: [
      "讨论作品，不攻击作者。",
      "引用他人文字时注明来源。",
      "管理员仅在违反社区规则时隐藏内容。",
    ],
  },
};
